# Generated by Django 4.1.7 on 2023-05-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siba_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_db',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student_db',
            name='upload_Result',
        ),
    ]
