# Generated by Django 4.1.7 on 2023-05-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siba_admin', '0002_delete_assignments'),
        ('siba_student', '0006_remove_student_db_id_alter_student_db_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_db',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siba_admin.courses'),
        ),
    ]
