# Generated by Django 4.1.7 on 2023-05-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siba_student', '0007_student_db_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_db',
            name='course',
        ),
    ]
