# Generated by Django 4.1.7 on 2023-05-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siba_student', '0010_remove_student_db_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_db',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20),
        ),
    ]
