# Generated by Django 4.1.7 on 2023-05-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siba_student', '0011_alter_student_db_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_db',
            name='age',
            field=models.CharField(max_length=200),
        ),
    ]
