# Generated by Django 4.1.7 on 2023-05-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siba_student', '0006_remove_student_db_id_alter_student_db_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siba_admin.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siba_student.student_db')),
            ],
        ),
    ]
