# Generated by Django 4.1.7 on 2023-05-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siba_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignments',
        ),
    ]
