# Generated by Django 4.1.7 on 2023-05-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siba_student', '0008_remove_student_db_course'),
        ('siba_admin', '0002_delete_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siba_admin.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siba_student.student_db')),
            ],
        ),
    ]
