# Generated by Django 4.1.7 on 2023-05-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siba_admin', '0003_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_Id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
