# Generated by Django 4.1.7 on 2023-05-31 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siba_admin', '0004_alter_courses_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('course_alloc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siba_admin.courses')),
            ],
        ),
    ]
