# Generated by Django 4.1.7 on 2023-06-03 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siba_admin', '0006_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='TimeGenerated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
